### ISSUE TITLE
Cannot play youtube videos, only 1 of 5-10 attempts is succesfull, 403 error

### ISSUE THREAD

**Issue by RuslanOrolbaev** [newtaDev/pod_player#142]
Hello, 
First, thank you for this great package, it is much faster than any players using webview! 

However, I experience the issue below:

when trying to initialize PodPlayerController, very rare it works but usually fails with the following  error:

_E/ExoPlayerImplInternal( 4568): Playback error
E/ExoPlayerImplInternal( 4568):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 4568):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal( 4568):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
E/ExoPlayerImplInternal( 4568):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 4568):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 4568):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4568):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: **Response code: 403**
E/ExoPlayerImplInternal( 4568):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:413)
E/ExoPlayerImplInternal( 4568):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
E/ExoPlayerImplInternal( 4568):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 4568):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
E/ExoPlayerImplInternal( 4568):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 4568):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 4568):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 4568):       at java.lang.Thread.run(Thread.java:923)
I/( 4568): Background concurrent copying GC freed 24665(2111KB) AllocSpace objects, 586(45MB) LOS objects, 22% free, 80MB/104MB, paused 1.442ms total 168.998ms
I/flutter ( 4568): SEVERE: 2023-08-10 10:42:19.373750: main: uncaught async error: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)_

Even if initialization is successful, the attempt to use the controller's changeVideo() method fails for sure. 
I tried versions 0.1.5 and 0.2.0 with the same result. Flutter version 3.10.6. 

Please advise on that. Thank you.

**Comment by 1041harpreet** [comment]
i am also getting the same issue. same video works sometime and sometime it is showing this error.

**Comment by amrhassann** [comment]
same here, any solutions?!

**Comment by kingyyy** [comment]
same here version 0.2.0

**Comment by SujitChanda** [comment]
Getting same issue, its been  >10 days

**Comment by jeffysmak** [comment]
Me too, getting same issue

**Comment by Joseph-Nathan** [comment]
me too!

**Comment by 1041harpreet** [comment]
looking for solution otherwise i have to use another package.

**Comment by Joseph-Nathan** [comment]
The problem with YouTube links it self

**Comment by rakib205** [comment]
Same here.
@newtaDev can you please look into this?

**Comment by GeorgeReda** [comment]
I solved the issue by upgrading the packages. the dependencies YouTube explode and http were old, so I upgraded them and now the video players works like a charm.
`https://github.com/GeorgeReda/pod_player`
that's my fork and I've made a PR.

**Comment by 1041harpreet** [comment]
> I solved the issue by upgrading the packages. the dependencies YouTube explode and http were old, so I upgraded them and now the video players works like a charm. `https://github.com/GeorgeReda/pod_player` that's my fork and I've made a PR.

what can we do now? like this issue will be resolved after admin will accept PR , so before this how can work with this pacakge.

**Comment by RuslanOrolbaev** [comment]
The package version 0.2.1 has been released, it seems the issue has been solved there

**Comment by newtaDev** [comment]
Upgraded all dependencies:
Please change pod_player version `0.2.1`

**Comment by mgarciareimers** [comment]
Hi, I am still having the issue. The version I use. is 0.2.1

This is the error: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D401F, -1, null, [1280, 720, 29.97003], [-1, -1]), format_supported=YES, null, null)

The video is played sometimes.

Thank you in advance!
