### ISSUE TITLE
===== VIMEO API ERROR: type 'Null' is not a subtype of type 'List<dynamic>' in type cast ==========

### ISSUE THREAD

**Issue by geek-aryan** [newtaDev/pod_player#193]
playVideoFrom: PlayVideoFrom.vimeo('518228118'), give me error

**Comment by geek-aryan** [comment]
playVideoFrom: PlayVideoFrom.vimeo('518228118'),

**Comment by GjoAbrahamN** [comment]
i also have the same issue. i have updated the package and it solved

**Comment by MrNaifpp** [comment]
same issue happened to me
i fix it by updating flutter version to 3.19.6 the latest flutter version.
Hope it help you

**Comment by mariobatista1** [comment]
I've updated the flutter and the package and the problem still persists
