### ISSUE TITLE
Unable to play vimeo videos

### ISSUE THREAD

**Issue by mohamed-belal1** [newtaDev/pod_player#242]
Hi, I am unable to play vimeo videos despite providing all the necessary parameters
`  @override
  void initState() {
    super.initState();
    controller = PodPlayerController(
      playVideoFrom: PlayVideoFrom.vimeo(
        '518228118',
        httpHeaders: {
          'Authorization': 'bearer #############'
        },
      ),
    )..initialise();
  }`
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/9171627c-2801-41c8-a20c-be1b334412bb">

**Comment by ge0rge000** [comment]
i have solution for get all quality contact with me :+971557474526

**Comment by mohamed-belal1** [comment]
Why don't you share your solution here so everyone can benefit from it?

**Comment by ge0rge000** [comment]
Because team make on it and solution is paid not free

**Comment by icecandy** [comment]
Maybe I'm just gullible, but I tried to contact @ge0rge000 to find out the solution to this problem and he wanted to charge me $300!!
In my many years as a developer I have never experienced this before. Disgusting behavior.

**Comment by icecandy** [comment]
But on a more constructive note (well sort of) I have this problem too. Even just trying to play a plain public vimeo video (not private or restricted).

**Comment by hopee-tien** [comment]
@icecandy 
Dear friend ! 
how is it for this case ?

**Comment by icecandy** [comment]
@beto-hopee I've given up. I have implemented Vimeo playback completely in vanilla javascript in a web view using the Vimeo API. I have also done the same with YouTube videos, with almost identical code (the API is a little different and so not quite the same implementation). My app allows people to build their own HTML blog page and so I am already in a web view by default and so this is a very suitable solution.

**Comment by hopee-tien** [comment]
@icecandy good solution, thanks for sharing your case 🙏

**Comment by mohamed-belal1** [comment]
Any update on this case? still cannot play vimeo videos in pod player

**Comment by leonardmatasel** [comment]
You could try [omni_video_player](https://pub.dev/packages/omni_video_player). It handles Vimeo and other video sources more reliably and doesn’t require complex platform view setup
